# Generated by Django 5.1.3 on 2024-11-30 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("age", models.IntegerField()),
                ("monthly_income", models.IntegerField()),
                ("phone_number", models.BigIntegerField()),
                ("approved_limit", models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Loan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("loan_amount", models.FloatField()),
                ("interest_rate", models.FloatField()),
                ("tenure", models.IntegerField()),
                ("is_approved", models.BooleanField(default=False)),
                ("monthly_installment", models.FloatField(blank=True, null=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="loans.customer"
                    ),
                ),
            ],
        ),
    ]
